import React,{useEffect,useState} from 'react';
import PhotoCarousel from './PhotoCarousel';
import {writePublication,loadPublication,savePublication,listPublications,switchPublication} from '../services/publicationService';
const empty={mode:'work',brief:'',topic:'',post:'',slides:[],carousel:false,sourcePost:'',style:'editorial'};
export default function PublicationEditor({scope,context,incoming}){
 const [draft,setDraft]=useState(empty),[loaded,setLoaded]=useState(false),[loadFailed,setLoadFailed]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[saved,setSaved]=useState('Загружаю черновик…'),[ideas,setIdeas]=useState([]),[instruction,setInstruction]=useState(''),[history,setHistory]=useState([]),[revision,setRevision]=useState(0),[carouselBusy,setCarouselBusy]=useState(false);
 useEffect(()=>{let live=true;loadPublication(scope).then(value=>{if(live){setDraft(value||empty);setSaved('Черновик на этом устройстве');}}).catch(()=>{if(live){setLoadFailed(true);setError('Не удалось открыть сохранённый черновик. Обновите страницу, чтобы повторить попытку.');}}).finally(()=>{if(live)setLoaded(true);});return()=>{live=false;};},[scope]);
 useEffect(()=>{if(!loaded||loadFailed)return;setSaved('Сохраняю…');savePublication(scope,draft).then(()=>setSaved('Сохранено на этом устройстве')).catch(()=>setSaved('Не удалось сохранить: возможно, недостаточно места. Скачайте результат перед выходом.'));},[draft,loaded,loadFailed,scope]);
 useEffect(()=>{listPublications(scope).then(setHistory).catch(()=>{});},[scope,revision]);
 async function openDraft(key){setBusy(true);setError('');try{const next=key?await loadPublication(key):{...empty,mode:draft.mode};if(!next)throw new Error('Не удалось найти публикацию');await switchPublication(scope,draft,next,key);setDraft(next);setIdeas([]);setInstruction('');setRevision(n=>n+1);}catch(e){setError(e.message||'Не удалось сохранить текущую публикацию. Переход отменён.');}finally{setBusy(false);}}
 const change=patch=>setDraft(prev=>({...prev,...patch}));
 async function run(action){setBusy(true);setError('');try{const result=await writePublication({action,mode:draft.mode,context,topic:draft.topic,brief:draft.brief,post:draft.post,instruction});if(action==='ideas')setIdeas(result);else change({post:result});}catch(e){setError(e.message);}finally{setBusy(false);}}
 if(!loaded)return <p>Загружаю черновик…</p>;
 if(loadFailed)return <p role="alert" className="text-red-600">{error}</p>;
 return <section className="p-5 border rounded-3xl space-y-4"><div className="flex items-center justify-between gap-3"><h3 className="font-bold">Публикация</h3>{(draft.post||draft.topic||draft.slides?.length>0)&&<button disabled={busy||carouselBusy} className="text-sm underline disabled:opacity-40" onClick={()=>openDraft()}>Новая публикация</button>}</div>{history.length>0&&<details><summary className="text-sm cursor-pointer">Сохранённые публикации ({history.length})</summary><div className="space-y-2 mt-2">{history.map(item=><button key={item.key} disabled={busy||carouselBusy} className="block text-left w-full border rounded-xl p-3 text-sm" onClick={()=>openDraft(item.key)}>{item.title}</button>)}</div></details>}<p className="text-xs text-slate-500">{saved}. Фото и текст не синхронизируются между устройствами.</p>
 {incoming&&draft.sourceId!==incoming.id&&<div className="p-3 border rounded-xl"><p className="text-sm">AI подготовил текст. Его можно перенести в редактор публикации.</p><button className="underline text-sm" disabled={busy||carouselBusy} onClick={()=>change({post:incoming.text,sourceId:incoming.id,carousel:false})}>Использовать текст AI</button></div>}
 <label className="text-sm">Контекст <select disabled={busy||carouselBusy} value={draft.mode} onChange={e=>{change({mode:e.target.value});setIdeas([]);}} className="border rounded-lg p-2 bg-transparent"><option value="work">О работе</option><option value="personal">Личное</option></select></label>
 {!draft.post&&<><textarea aria-label="Тема публикации" className="w-full border rounded-xl p-3 bg-transparent" maxLength={4000} value={draft.topic} onChange={e=>change({topic:e.target.value})} placeholder={draft.mode==='personal'?'О чём хочется рассказать? Можно начать с мысли или события.':'О чём написать? Или предложить темы по вашему профилю.'}/><div className="flex gap-3"><button disabled={busy||carouselBusy} className="border rounded-xl p-3 disabled:opacity-40" onClick={()=>run('ideas')}>Предложить темы</button><button disabled={busy||carouselBusy||!draft.topic.trim()} className="border rounded-xl p-3 disabled:opacity-40" onClick={()=>run('post')}>Написать пост</button></div>{ideas.map((idea,i)=><button className="block w-full text-left border rounded-xl p-3" key={i} disabled={busy||carouselBusy} onClick={()=>{change({topic:idea,brief:draft.brief||draft.topic});setIdeas([]);}}>{idea}</button>)}<details><summary className="text-sm cursor-pointer">У меня уже есть текст</summary><textarea aria-label="Вставить готовый пост" className="w-full border p-3 bg-transparent" onBlur={e=>{if(e.target.value.trim())change({post:e.target.value});}} placeholder="Вставьте текст и нажмите вне поля"/></details></>}
 {draft.post&&<><label className="block text-sm">Пост — можно редактировать<textarea aria-label="Текст публикации" className="block w-full border rounded-xl p-3 bg-transparent" rows={10} maxLength={12000} value={draft.post} disabled={busy||carouselBusy} onChange={e=>change({post:e.target.value})}/></label><div className="flex gap-2"><input aria-label="Правка поста" className="flex-1 min-w-0 border rounded-xl p-2 bg-transparent" value={instruction} onChange={e=>setInstruction(e.target.value)} placeholder="Например: короче и теплее"/><button disabled={busy||carouselBusy||!instruction.trim()} onClick={()=>run('revise')}>Применить</button></div><div className="flex gap-3"><button className="border rounded-xl p-3" disabled={busy||carouselBusy} onClick={()=>change({carousel:!draft.carousel,sourcePost:draft.sourcePost||draft.post})}>{draft.carousel?'Скрыть карусель':'Сделать карусель'}</button><button onClick={()=>navigator.clipboard.writeText(draft.post).catch(()=>setError('Не удалось скопировать. Выделите текст вручную.'))}>Скопировать пост</button></div></>}
 {error&&<p role="alert" className="text-red-600">{error}</p>}{busy&&<p role="status">Готовлю текст…</p>}
 {draft.carousel&&<>{draft.sourcePost!==draft.post&&<p className="text-sm text-amber-700">Пост изменён. Слайды остаются прежними; Кнопка «Создать карусель» обновит их из текущего поста.</p>}<PhotoCarousel key={revision} onBusyChange={setCarouselBusy} regenerateText={draft.sourcePost!==draft.post} sourcePost={draft.post} initialSlides={draft.slides} initialStyle={draft.style} initialExports={draft.exports||[]} onDraftChange={(slides,style,exports)=>change({slides,style,exports})} onTextGenerated={()=>change({sourcePost:draft.post})}/></>}
 </section>;
}
