import React from 'react';
import {render,screen,fireEvent,waitFor} from '@testing-library/react';
import PublicationEditor from './PublicationEditor';
import {loadPublication,savePublication,writePublication,listPublications,switchPublication} from '../services/publicationService';
jest.mock('../services/publicationService',()=>({loadPublication:jest.fn(),savePublication:jest.fn(),writePublication:jest.fn(),listPublications:jest.fn(),switchPublication:jest.fn()}));
jest.mock('./PhotoCarousel',()=>({sourcePost})=><div>Карусель: {sourcePost}</div>);
beforeEach(()=>{jest.clearAllMocks();listPublications.mockResolvedValue([]);switchPublication.mockResolvedValue();loadPublication.mockResolvedValue(null);savePublication.mockResolvedValue();});
test('imports only after confirmation, uses edited post and persists scope',async()=>{loadPublication.mockResolvedValue({mode:'work',post:'Старый пост',slides:[],carousel:false});render(<PublicationEditor scope="u:personal:a" incoming={{id:'new',text:'Новый пост'}}/>);await screen.findByDisplayValue('Старый пост');fireEvent.click(screen.getByText('Использовать текст AI'));fireEvent.change(screen.getByLabelText('Текст публикации'),{target:{value:'Исправленный пост'}});fireEvent.click(screen.getByText('Сделать карусель'));expect(screen.getByText('Карусель: Исправленный пост')).toBeInTheDocument();await waitFor(()=>expect(savePublication).toHaveBeenLastCalledWith('u:personal:a',expect.objectContaining({post:'Исправленный пост',carousel:true})));});
test('suggested topic becomes the next post input',async()=>{writePublication.mockResolvedValue(['Тема о конфликтах']);render(<PublicationEditor scope="u:company:a" context={{products:'Обучение'}}/>);await screen.findByText('Предложить темы');fireEvent.change(screen.getByLabelText('Тема публикации'),{target:{value:'Помогаю руководителям разрешать конфликты'}});fireEvent.click(screen.getByText('Предложить темы'));fireEvent.click(await screen.findByText('Тема о конфликтах'));expect(screen.getByLabelText('Тема публикации')).toHaveValue('Тема о конфликтах');writePublication.mockResolvedValue('Готовый пост');fireEvent.click(screen.getByText('Написать пост'));await screen.findByDisplayValue('Готовый пост');expect(writePublication).toHaveBeenLastCalledWith(expect.objectContaining({topic:'Тема о конфликтах',brief:'Помогаю руководителям разрешать конфликты',action:'post'}));});
test('failed draft load never overwrites the saved publication',async()=>{
 loadPublication.mockRejectedValue(new Error('Storage unavailable'));
 render(<PublicationEditor scope="u:company:a"/>);
 expect(await screen.findByRole('alert')).toHaveTextContent('Не удалось открыть');
 expect(savePublication).not.toHaveBeenCalled();
 expect(screen.queryByText('Предложить темы')).not.toBeInTheDocument();
});

test('new publication archives current draft before clearing editor',async()=>{loadPublication.mockResolvedValue({mode:'work',post:'Сохранить этот пост',slides:[],carousel:false});render(<PublicationEditor scope="u:company:a"/>);await screen.findByDisplayValue('Сохранить этот пост');fireEvent.click(screen.getByText('Новая публикация'));await screen.findByText('Предложить темы');expect(switchPublication).toHaveBeenCalledWith('u:company:a',expect.objectContaining({post:'Сохранить этот пост'}),expect.objectContaining({post:''}),undefined);});
test('archive failure keeps current post',async()=>{loadPublication.mockResolvedValue({mode:'work',post:'Не потерять',slides:[],carousel:false});switchPublication.mockRejectedValue(new Error('Нет места'));render(<PublicationEditor scope="u:company:a"/>);await screen.findByDisplayValue('Не потерять');fireEvent.click(screen.getByText('Новая публикация'));await screen.findByRole('alert');expect(screen.getByDisplayValue('Не потерять')).toBeInTheDocument();});
test('opening history moves that copy into the editor',async()=>{const key='u:company:a:history:1:x';listPublications.mockResolvedValue([{key,title:'Старый пост',savedAt:1}]);loadPublication.mockResolvedValueOnce(null).mockResolvedValueOnce({mode:'work',post:'Старый пост',slides:[],carousel:false});render(<PublicationEditor scope="u:company:a"/>);fireEvent.click(await screen.findByText('Сохранённые публикации (1)'));fireEvent.click(screen.getByText('Старый пост'));await screen.findByDisplayValue('Старый пост');expect(switchPublication).toHaveBeenCalledWith('u:company:a',expect.objectContaining({post:''}),expect.objectContaining({post:'Старый пост'}),key);});
